In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

/kaggle/input/amazon-alexa-reviews/amazon_alexa.tsv


In [2]:
train = pd.read_csv('/kaggle/input/amazon-alexa-reviews/amazon_alexa.tsv' , delimiter = '\t' ,usecols = ['verified_reviews' , 'feedback'] )

In [3]:
train[train.feedback==0]

verified_reviews  feedback
46    It's like Siri, in fact, Siri answers more acc...         0
111   Sound is terrible if u want good music too get...         0
141                                  Not much features.         0
162   Stopped working after 2 weeks ,didn't follow c...         0
176                                Sad joke. Worthless.         0
...                                                 ...       ...
3047  Echo Dot responds to us when we aren't even ta...         0
3048              NOT CONNECTED TO MY PHONE PLAYLIST :(         0
3067  The only negative we have on this product is t...         0
3091                                  I didn’t order it         0
3096  The product sounded the same as the emoji spea...         0

[257 rows x 2 columns]

In [4]:
train.head(50)

verified_reviews  feedback
0                                       Love my Echo!         1
1                                           Loved it!         1
2   Sometimes while playing a game, you can answer...         1
3   I have had a lot of fun with this thing. My 4 ...         1
4                                               Music         1
5   I received the echo as a gift. I needed anothe...         1
6   Without having a cellphone, I cannot use many ...         1
7   I think this is the 5th one I've purchased. I'...         1
8                                         looks great         1
9   Love it! I’ve listened to songs I haven’t hear...         1
10  I sent it to my 85 year old Dad, and he talks ...         1
11  I love it! Learning knew things with it eveyda...         1
12  I purchased this for my mother who is having k...         1
13                                 Love, Love, Love!!         1
14                           Just what I expected....         1
15                          I love it, wife hates it.         1
16  Really happy with this purchase.  Great speake...         1
17  We have only been using Alexa for a couple of ...         1
18  We love the size of the 2nd generation echo. S...         1
19  I liked the original Echo. This is the same bu...         1
20  Love the Echo and how good the music sounds pl...         1
21  We love Alexa! We use her to play music, play ...         1
22  Have only had it set up for a few days. Still ...         1
23  I love it. It plays my sleep sounds immediatel...         1
24  I got a second unit for the bedroom, I was exp...         1
25                                    Amazing product         1
26  I love my Echo. It's easy to operate, loads of...         1
27                          Sounds great!! Love them!         1
28  Fun item to play with and get used to using.  ...         1
29                            Just like the other one         1
30  Still learning all the capabilities...but so f...         1
31                                          I like it         1
32  She works well. Needs a learning command  for ...         1
33  The speakers sound pretty good for being so sm...         1
34                            This device is awesome!         1
35  I bought this to compare the speaker quality t...         1
36  Love my Echo. Still learning all the things it...         1
37         Speaker is better than 1st generation Echo         1
38  This thing is way cool!  You should get one.  ...         1
39  This is my first digital assistant so I'm givi...         1
40  My husband likes being able to use it to liste...         1
41  My Android would not allow Alexa to connect. F...         1
42                                     So far so good         1
43  Tried to play certain broadway shows like Came...         1
44                                              Great         1
45  Very satisfied with the Echo. Alexa now contro...         1
46  It's like Siri, in fact, Siri answers more acc...         0
47  Love my Echo. Still learning how every thing w...         1
48                                 I love you so much         1
49  No different than Apple. To play a specific li...         1

In [5]:
train =train.rename(columns={'verified_reviews':'reviews'})

In [6]:
train.head()

reviews  feedback
0                                      Love my Echo!         1
1                                          Loved it!         1
2  Sometimes while playing a game, you can answer...         1
3  I have had a lot of fun with this thing. My 4 ...         1
4                                              Music         1

In [7]:
train.isnull().any()

reviews     False
feedback    False
dtype: bool

In [8]:
stopword={'a','about','above','after','again','against','all','am','an','and','any','are','as','at','be','because','been','before',
'being','below','between','both','but','by','can',
'd',
'did',
'do',
'does',
'doing',
'down',
'during',
'each',
'few',
'for',
'from',
'further',
'had',
'has',
'hasn',
"hasn't",
'have',
'having',
'he',
'her',
'here',
'hers',
'herself',
'him',
'himself','his',
'how',
'i',
'if',
'in',
'into',
'is',
'it',
"it's",
'its',
'itself',
'just',
'll',
'm',
'ma',
'me',
'more',
'most',
'my',
'myself',
'no',
'now',
'o',
'of',
'off',
'on',
'once',
'only','or',
'other',
'our',
'ours',
'ourselves',
'out',
'over',
'own',
're',
's',
'same',
'she',
"she's",
'should',
"should've",
'so',
'some',
'such',
't',
'than',
'that',
"that'll",
'the',
'their',
'theirs',
'them',
'themselves',
'then','there',
'these',
'they',
'this',
'those',
'through',
'to',
'too',
'under',
'until',
'up',
've',
'very',
'was',
'we',
'were',
'what',
'when',
'where',
'which',
'while',
'who',
'whom',
'why','will',
'with',
'y',
'you',
"you'd",
"you'll",
"you're",
"you've",
'your',
'yours',
'yourself',
'yourselves'}


In [9]:
train.shape

(3150, 2)

In [10]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
TEXT_CLEANING_RE = "@\S+|https?:\S+|http?:\S|[^A-Za-z0-9]+"
corpus=[]
for i in range(0,3150):
    review = re.sub(TEXT_CLEANING_RE, ' ', train['reviews'][i] )
    review=review.lower()
    review=review.split()
    ps=PorterStemmer()
    review=[ps.stem(word) for word in review if not word in set(stopword)]
    review=' '.join(review)
    corpus.append(review)

In [11]:
corpus


['love echo',
 'love',
 'sometim play game answer question correctli alexa say got wrong answer like abl turn light away home',
 'lot fun thing 4 yr old learn dinosaur control light play game like categori nice sound play music well',
 'music',
 'receiv echo gift need anoth bluetooth someth play music easili access found smart speaker wait see els',
 'without cellphon cannot use mani featur ipad not see use great alarm u r almost deaf hear alarm bedroom live room reason enough keep fun ask random question hear respons not seem smartbon polit yet',
 'think 5th one purchas work get one everi room hous realli like featur offer specifili play music echo control light throughout hous',
 'look great',
 'love listen song haven heard sinc childhood get news weather inform great',
 'sent 85 year old dad talk constantli',
 'love learn knew thing eveyday still figur everyth work far easi use understand make laugh time',
 'purchas mother knee problem give someth tri come not get around fast like e

In [12]:
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer

In [13]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=2800)
vec = TfidfVectorizer(strip_accents='unicode', use_idf=1, smooth_idf=1, sublinear_tf=1 )
X=vec.fit_transform(corpus).toarray()
y=train.iloc[:,1].values

In [14]:
y

array([1, 1, 1, ..., 1, 1, 1])

In [15]:
X

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [16]:
X.shape

(3150, 2837)

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [18]:
import xgboost as xgb
from xgboost import XGBClassifier
classifier = XGBClassifier()
classifier.fit(X_train, y_train)

XGBClassifier(base_score=0.5, booster=None, colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints=None,
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=0, num_parallel_tree=1,
              objective='binary:logistic', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=1, subsample=1, tree_method=None,
              validate_parameters=False, verbosity=None)

In [19]:
y_pred = classifier.predict(X_test)

In [20]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [21]:
cm

array([[ 25,  29],
       [  4, 572]])